### ISSUE TITLE
Will it work with multidimensional array?

### ISSUE THREAD

**Issue by fahmiegerton** [touhidurabir/laravel-model-sanitize#1]
As the title said, I tried to create from this data :
```
$data = [
    [ 'name' => 'someone', 'related_item' => 2, 'pickby' => 3],
    [ 'name' => 'another one', 'related_item' => 1, 'pickby' => 4]
];
```
I tried it with `create` method but I check the query it all gone. So, is this library works with multidimensional array, or not? if it's supposed to work, could you help me why my data is gone before insert? thanks!

**Comment by touhidurabir** [comment]
No it will not work for multidimensional array as what is does is just sanitize the given data based on model fillable, guarded and table schema . it does not override the behaviour of eloquent methods . And none of the eloquent methods take multi dimension array to create/update multiple records at the same time . To accomplish that you have to use Query Builder or DB class .
